spring.application.name=instant-bank-backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/instant_bank?createDatabaseIfNotExist=true&serverTimezone=Asia/Kuala_Lumpur
spring.datasource.username=root
spring.datasource.password=Wong_0819

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080